### PR TITLE
Fix new pack formatting, add blank cards

### PR DESCRIPTION
**Pull request by LRitzdorf**
This PR fixes small consistency issues with the six (or eight, since three are bundled together in one file) new card packs added by #18. Most notably, periods at the ends of response cards have been removed, and blank cards have been added (currently at about a 1% rate, but preferably in the same number as are in the physical card boxes).

### CODE REVIEW

**Comment by LRitzdorf** [comment]
Will be marked as "ready for review" (not a draft) when the number of blank cards included in the physical CAH decks are added to deck files here.

**Comment by LRitzdorf** [comment]
Okay, it looks like finding out how many blanks are in the physical packs will be rather difficult. Since this can always be changed later, I'm marking this PR as ready to merge.

**Comment by LRitzdorf** [comment]
Note: that force-push was for a typo in the commit message (made via Termux from my phone)

**Comment by jonas747** [comment]
Looks good! probably something i shouldve done myself...

**Pull request merged**
